[package]
name = "pi-calc-wasm"
version = "0.1.0"
authors = ["Ben Ford <ford2bm@gmail.com>"]
edition = "2018"


[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
